In [49]:
import numpy as np

In [50]:
document_test = ["youpi","le","chien","est","heureux","devant","le","camaieu"]

In [51]:
def create_HAL_matrix(document):
    words = []
    for word in document:
        if word not in words:
            words.append(word)
    n = len(words)
    hal_dict_matrix = {}
    for word in words:
        hal_dict_matrix[word]={}
        for word2 in words:
            hal_dict_matrix[word][word2] = 0
        
    return hal_dict_matrix

In [52]:
hal_dict_matrix_test= create_HAL_matrix(document_test)

In [53]:
list(list(hal_dict_matrix_test.values())[0].values())

[0, 0, 0, 0, 0, 0, 0]

In [54]:
def fill_HAL_matrix(document,hal_dict_matrix,window_size):
    window_size_updated = window_size
    len_doc = len(document)
    for i in range(len_doc):
        word = document[i]
        if i+window_size >=len_doc:
            window_size_updated += -1
        for k in range(1,window_size_updated+1):
            word2 = document[i+k]
            hal_dict_matrix[word][word2] += window_size-k+1
    return hal_dict_matrix

In [55]:
fill_HAL_matrix(document_test,hal_dict_matrix_test,window_size=5)

{'youpi': {'youpi': 0,
  'le': 5,
  'chien': 4,
  'est': 3,
  'heureux': 2,
  'devant': 1,
  'camaieu': 0},
 'le': {'youpi': 0,
  'le': 1,
  'chien': 5,
  'est': 4,
  'heureux': 3,
  'devant': 2,
  'camaieu': 5},
 'chien': {'youpi': 0,
  'le': 2,
  'chien': 0,
  'est': 5,
  'heureux': 4,
  'devant': 3,
  'camaieu': 1},
 'est': {'youpi': 0,
  'le': 3,
  'chien': 0,
  'est': 0,
  'heureux': 5,
  'devant': 4,
  'camaieu': 2},
 'heureux': {'youpi': 0,
  'le': 4,
  'chien': 0,
  'est': 0,
  'heureux': 0,
  'devant': 5,
  'camaieu': 3},
 'devant': {'youpi': 0,
  'le': 5,
  'chien': 0,
  'est': 0,
  'heureux': 0,
  'devant': 0,
  'camaieu': 4},
 'camaieu': {'youpi': 0,
  'le': 0,
  'chien': 0,
  'est': 0,
  'heureux': 0,
  'devant': 0,
  'camaieu': 0}}

In [56]:
def hal_dict_to_matrix(hal_dict_matrix):
    hal_matrix = []
    for i in range(len(hal_dict_matrix.keys())):
        hal_matrix.append(list(list(hal_dict_matrix_test.values())[i].values()))
    return hal_matrix,list(hal_dict_matrix.keys())

In [57]:
hal_matrix_test,words_list_test = hal_dict_to_matrix(hal_dict_matrix_test)
hal_matrix_test

[[0, 5, 4, 3, 2, 1, 0],
 [0, 1, 5, 4, 3, 2, 5],
 [0, 2, 0, 5, 4, 3, 1],
 [0, 3, 0, 0, 5, 4, 2],
 [0, 4, 0, 0, 0, 5, 3],
 [0, 5, 0, 0, 0, 0, 4],
 [0, 0, 0, 0, 0, 0, 0]]

In [58]:
def hal_to_symmetric(hal_matrix):
    return hal_matrix + np.transpose(hal_matrix)

In [59]:
hal_matrix_symmetric_test = hal_to_symmetric(hal_matrix_test)
hal_matrix_symmetric_test

array([[0, 5, 4, 3, 2, 1, 0],
       [5, 2, 7, 7, 7, 7, 5],
       [4, 7, 0, 5, 4, 3, 1],
       [3, 7, 5, 0, 5, 4, 2],
       [2, 7, 4, 5, 0, 5, 3],
       [1, 7, 3, 4, 5, 0, 4],
       [0, 5, 1, 2, 3, 4, 0]])

In [60]:
words_list_test

['youpi', 'le', 'chien', 'est', 'heureux', 'devant', 'camaieu']

In [61]:
def document_vector(hal_matrix_symmetric):
    n_words = len(hal_matrix_symmetric)
    doc_vector = np.array([0]*n_words)
    for i in range(n_words):
        doc_vector[i] = sum(hal_matrix_symmetric[i])
    return doc_vector

In [62]:
document_vector(hal_matrix_symmetric_test)

array([15, 40, 24, 26, 26, 24, 15])

In [63]:
def extract_word_vector(hal_matrix_symmetric,words_list,word_to_extract):
    word_position = words_list.index(word_to_extract)
    return hal_matrix_symmetric[word_position]

In [64]:
word_vector_test = extract_word_vector(hal_matrix_symmetric_test,words_list_test,"le")
word_vector_test

array([5, 2, 7, 7, 7, 7, 5])

In [65]:
def normalize_vector(word_vector):
    return word_vector/(np.linalg.vector_norm(word_vector))

In [66]:
normalize_vector(word_vector_test)

array([0.31622777, 0.12649111, 0.44271887, 0.44271887, 0.44271887,
       0.44271887, 0.31622777])