In [146]:
import numpy as np

In [147]:
document_test = ["youpi","le","chien","est","heureux","devant","le","camaieu"]

In [148]:
def create_HAL_matrix(document):
    words = []
    for word in document:
        if word not in words:
            words.append(word)
    n = len(words)
    hal_dict_matrix = {}
    for word in words:
        hal_dict_matrix[word]={}
        for word2 in words:
            hal_dict_matrix[word][word2] = 0
        
    return hal_dict_matrix

In [149]:
hal_dict_matrix_test= create_HAL_matrix(document_test)

In [150]:
list(list(hal_dict_matrix_test.values())[0].values())

[0, 0, 0, 0, 0, 0, 0]

In [151]:
def fill_HAL_matrix(document,hal_dict_matrix,window_size):
    window_size_updated = window_size
    len_doc = len(document)
    for i in range(len_doc):
        word = document[i]
        if i+window_size >=len_doc:
            window_size_updated += -1
        for k in range(1,window_size_updated+1):
            word2 = document[i+k]
            hal_dict_matrix[word][word2] += window_size-k+1
    return hal_dict_matrix

In [152]:
fill_HAL_matrix(document_test,hal_dict_matrix_test,window_size=5)

{'youpi': {'youpi': 0,
  'le': 5,
  'chien': 4,
  'est': 3,
  'heureux': 2,
  'devant': 1,
  'camaieu': 0},
 'le': {'youpi': 0,
  'le': 1,
  'chien': 5,
  'est': 4,
  'heureux': 3,
  'devant': 2,
  'camaieu': 5},
 'chien': {'youpi': 0,
  'le': 2,
  'chien': 0,
  'est': 5,
  'heureux': 4,
  'devant': 3,
  'camaieu': 1},
 'est': {'youpi': 0,
  'le': 3,
  'chien': 0,
  'est': 0,
  'heureux': 5,
  'devant': 4,
  'camaieu': 2},
 'heureux': {'youpi': 0,
  'le': 4,
  'chien': 0,
  'est': 0,
  'heureux': 0,
  'devant': 5,
  'camaieu': 3},
 'devant': {'youpi': 0,
  'le': 5,
  'chien': 0,
  'est': 0,
  'heureux': 0,
  'devant': 0,
  'camaieu': 4},
 'camaieu': {'youpi': 0,
  'le': 0,
  'chien': 0,
  'est': 0,
  'heureux': 0,
  'devant': 0,
  'camaieu': 0}}

In [153]:
def hal_dict_to_matrix(hal_dict_matrix):
    hal_matrix = []
    for i in range(len(hal_dict_matrix.keys())):
        hal_matrix.append(list(list(hal_dict_matrix_test.values())[i].values()))
    return hal_matrix,list(hal_dict_matrix.keys())

In [154]:
hal_matrix_test,words_list_test = hal_dict_to_matrix(hal_dict_matrix_test)
hal_matrix_test

[[0, 5, 4, 3, 2, 1, 0],
 [0, 1, 5, 4, 3, 2, 5],
 [0, 2, 0, 5, 4, 3, 1],
 [0, 3, 0, 0, 5, 4, 2],
 [0, 4, 0, 0, 0, 5, 3],
 [0, 5, 0, 0, 0, 0, 4],
 [0, 0, 0, 0, 0, 0, 0]]

In [155]:
def hal_to_symmetric(hal_matrix):
    return hal_matrix + np.transpose(hal_matrix)

In [156]:
hal_matrix_symmetric_test = hal_to_symmetric(hal_matrix_test)
hal_matrix_symmetric_test

array([[0, 5, 4, 3, 2, 1, 0],
       [5, 2, 7, 7, 7, 7, 5],
       [4, 7, 0, 5, 4, 3, 1],
       [3, 7, 5, 0, 5, 4, 2],
       [2, 7, 4, 5, 0, 5, 3],
       [1, 7, 3, 4, 5, 0, 4],
       [0, 5, 1, 2, 3, 4, 0]])

In [157]:
words_list_test

['youpi', 'le', 'chien', 'est', 'heureux', 'devant', 'camaieu']

In [158]:
def document_vector(hal_matrix_symmetric):
    n_words = len(hal_matrix_symmetric)
    doc_vector = np.array([0]*n_words)
    for i in range(n_words):
        doc_vector[i] = sum(hal_matrix_symmetric[i])
    return doc_vector

In [159]:
document_vector_test = document_vector(hal_matrix_symmetric_test)
document_vector_test

array([15, 40, 24, 26, 26, 24, 15])

In [160]:
def extract_word_vector(hal_matrix_symmetric,words_list,word_to_extract):
    word_position = words_list.index(word_to_extract)
    return hal_matrix_symmetric[word_position]

In [161]:
word_vector_test = extract_word_vector(hal_matrix_symmetric_test,words_list_test,"heureux")
word_vector_test

array([2, 7, 4, 5, 0, 5, 3])

In [162]:
word_vector_test2 = extract_word_vector(hal_matrix_symmetric_test,words_list_test,"chien")
word_vector_test2

array([4, 7, 0, 5, 4, 3, 1])

In [163]:
def normalize_vector(word_vector):
    return word_vector/(np.linalg.vector_norm(word_vector))

In [164]:
normalize_vector(word_vector_test)

array([0.1767767 , 0.61871843, 0.35355339, 0.44194174, 0.        ,
       0.44194174, 0.26516504])

In [165]:
def base_from_word_vectors(word_vector_normalised,word_vector_normalised2):
    word_vector_ort = word_vector_normalised2 - np.dot(word_vector_normalised2,word_vector_normalised)*word_vector_normalised
    word_vector_normalised_ort = normalize_vector(word_vector_ort)
    return word_vector_normalised,word_vector_normalised_ort

In [166]:
word_vector_test_normed = normalize_vector(word_vector_test)
word_vector_test_normed2 = normalize_vector(word_vector_test2)
base_vector1_test,base_vector2_test = base_from_word_vectors(word_vector_test_normed,word_vector_test_normed2)
base_from_word_vectors(word_vector_test_normed,word_vector_test_normed2)

(array([0.1767767 , 0.61871843, 0.35355339, 0.44194174, 0.        ,
        0.44194174, 0.26516504]),
 array([ 0.39606668,  0.24881112, -0.50777779,  0.17772223,  0.64995557,
        -0.14725556, -0.21834445]))

In [167]:
np.dot(base_vector1_test,base_vector2_test)

np.float64(1.2575874026256565e-16)

In [171]:
def project_doc_onto_base(base_vector1,base_vector2,document_vector):
    
    alpha = np.dot(base_vector1,document_vector)
    alpha_ort = np.dot(base_vector2,document_vector)
    normalisation_factor = np.sqrt(alpha**2+alpha_ort**2)
    return alpha/normalisation_factor,alpha_ort/normalisation_factor

In [172]:
alpha_test,alpha_ort_test = project_doc_onto_base(base_vector1_test,base_vector2_test,document_vector_test)
alpha_test,alpha_ort_test

(np.float64(0.9585511833141687), np.float64(0.28492039057780144))

In [173]:
np.sqrt(alpha_test**2+alpha_ort_test**2)

(np.float64(0.9999999999999999), np.float64(67.48333127521195))

In [190]:
def B_matrices(base_vector1,word_vector_normed2):
    p = np.dot(base_vector1,word_vector_normed2)
    B_mat = np.array([[2*p**2-1 ,2*p*np.sqrt(1-p**2)],[2*p*np.sqrt(1-p**2),1-2*p**2]])
    B_mat_x = np.array([[-2*p*np.sqrt(1-p**2),2*p**2-1],[2*p**2-1,2*p*np.sqrt(1-p**2)]])
    B_mat_plus = -(B_mat+B_mat_x)/np.sqrt(2)
    B_mat_minus = (B_mat-B_mat_x)/np.sqrt(2)
    return B_mat_plus,B_mat_minus

In [200]:
B_mat_plus_test,B_mat_minus_test = B_matrices(base_vector1_test,word_vector_test_normed2)
B_mat_plus_test,B_mat_minus_test

(array([[ 0.41782144, -0.90852916],
        [-0.90852916, -0.41782144]]),
 array([[ 0.90852916,  0.41782144],
        [ 0.41782144, -0.90852916]]))

In [192]:
A_mat = [[1,0],[0,-1]]
A_mat_x = [[0,1],[1,0]]

In [197]:
def esp(alpha,alpha_ort,matrix):
    document_vector = np.array([alpha,alpha_ort])
    return np.dot( document_vector,np.matmul(matrix,document_vector))

In [198]:
esp(alpha_test,alpha_ort_test,A_mat),2*alpha_test**2-1

(np.float64(0.837640742065986), np.float64(0.8376407420659859))

In [199]:
def S_query(A_mat,A_mat_x,B_mat_plus,B_mat_minus,alpha,alpha_ort):
    esp_A_Bplus = esp(alpha,alpha_ort,np.matmul(A_mat,B_mat_plus))
    esp_Ax_Bplus = esp(alpha,alpha_ort,np.matmul(A_mat_x,B_mat_plus))
    esp_A_Bminus = esp(alpha,alpha_ort,np.matmul(A_mat,B_mat_minus))
    esp_Ax_Bminus = esp(alpha,alpha_ort,np.matmul(A_mat_x,B_mat_minus))
    return np.abs(esp_A_Bplus + esp_Ax_Bplus) + np.abs(esp_A_Bminus - esp_Ax_Bminus)

In [201]:
S_query(A_mat,A_mat_x,B_mat_plus_test,B_mat_minus_test,alpha_test,alpha_ort_test)

np.float64(0.490707723151009)